### ISSUE TITLE
考虑私有部署或者docker吗

### ISSUE THREAD

**Issue by banjuer** [openneno/neno#12]
用github总会有网络不稳定的问题

**Comment by Mran** [comment]
这个项目的前端是可以部署在vercel或者cloudflare这样的平台上的，当然也可以部署在你的服务器上。
严格来说这个项目没有后端，因为数据存储是依赖与github的。
如果你不想使用github，那可以自己部署一个gitea，也是可以的。
当然，目前这个功能正在开发当中。
