### ISSUE TITLE
Vercel 部署 NENO 设置信息页面无法滚动

### ISSUE THREAD

**Issue by SkysCrystal** [openneno/neno#17]
在 Vercel 上部署 NENO
使用 Chrome 登录
第一次登录时，设置界面，点击同步到 Notion 后弹出新的内容，使得保存按钮移到到下方，此时页面没有滚动条，点击不到。问题同样在手机safari上出现。

![bug](https://user-images.githubusercontent.com/49473463/155560436-e47d651e-f21b-4ec5-9ecf-1d4b3a9ad510.png)

Chrome可以通过缩小页面点到保存，而Safari还没找到办法解决。烦请查修此Bug，谢谢！

**Comment by Mran** [comment]
cfa7c1da6cf71ccc1c6b6ba0b9d06c67d6cf85a2
