### ISSUE TITLE
搞个api呀

### ISSUE THREAD

**Issue by pxd0207** [openneno/neno#9]

**Comment by pxd0207** [comment]
微信输入

**Comment by Mran** [comment]
好的,正在搞

**Comment by pxd0207** [comment]
最好有telegram输入的api🤣

**Comment by Mran** [comment]
@pxd0207 搞定
https://github.com/Mran/neno-wx

**Comment by pxd0207** [comment]
厉害呀，telegram api可以搞么？

**Comment by Mran** [comment]
> 厉害呀，telegram api可以搞么？

应该可以，我看下

**Comment by Mran** [comment]
@pxd0207 搞定 https://github.com/openneno/neno-tg
